version: "3"

services:
  db:
    image: postgres
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Zoro15510990lufy

  app:
    image: python:3.8
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "pip install psycopg2-binary && python main.py"
    depends_on:
      - db
